# copyright [2025]
# description: Learning C++
# update-date: 2025年8月22日
# update-author: <李晟泽>
##############################################################################################
cmake_minimum_required(VERSION 3.12)
project(standard)

# add_subdirectory(17)
# add_subdirectory(20)

add_subdirectory(exam)

