# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='market_data.proto',
  package='Proto3.MarketData',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11market_data.proto\x12\x11Proto3.MarketData\")\n\x07\x44\x65\x63imal\x12\r\n\x05value\x18\x01 \x01(\x04\x12\x0f\n\x07precise\x18\x02 \x01(\r\"\x82\x02\n\x05\x44\x65pth\x12)\n\x05price\x18\x01 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12*\n\x06volume\x18\x02 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12L\n\x13volume_by_exchanges\x18\x03 \x03(\x0b\x32/.Proto3.MarketData.Depth.VolumeByExchangesEntry\x1aT\n\x16VolumeByExchangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal:\x02\x38\x01\"\xaa\x02\n\nDepthQuote\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x13\n\x0bsequence_no\x18\x03 \x01(\x04\x12\x13\n\x0borigin_time\x18\x04 \x01(\x04\x12\x13\n\x0b\x61rrive_time\x18\x05 \x01(\x04\x12\x13\n\x0bserver_time\x18\x06 \x01(\x04\x12\x15\n\rprice_precise\x18\x07 \x01(\r\x12\x16\n\x0evolume_precise\x18\x08 \x01(\r\x12\x16\n\x0e\x61mount_precise\x18\t \x01(\r\x12\x0f\n\x07is_snap\x18\n \x01(\x08\x12&\n\x04\x61sks\x18\x0b \x03(\x0b\x32\x18.Proto3.MarketData.Depth\x12&\n\x04\x62ids\x18\x0c \x03(\x0b\x32\x18.Proto3.MarketData.Depth\"\xaf\x02\n\tKlineData\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12+\n\x07px_open\x18\x04 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12+\n\x07px_high\x18\x05 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12*\n\x06px_low\x18\x06 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12,\n\x08px_close\x18\x07 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12*\n\x06volume\x18\x08 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12\x12\n\nresolution\x18\t \x01(\r\"\x92\x01\n\tTradeData\x12\x0c\n\x04time\x18\x01 \x01(\x04\x12)\n\x05price\x18\x02 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12*\n\x06volume\x18\x03 \x01(\x0b\x32\x1a.Proto3.MarketData.Decimal\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x10\n\x08\x65xchange\x18\x05 \x01(\tb\x06proto3'
)




_DECIMAL = _descriptor.Descriptor(
  name='Decimal',
  full_name='Proto3.MarketData.Decimal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto3.MarketData.Decimal.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='precise', full_name='Proto3.MarketData.Decimal.precise', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=81,
)


_DEPTH_VOLUMEBYEXCHANGESENTRY = _descriptor.Descriptor(
  name='VolumeByExchangesEntry',
  full_name='Proto3.MarketData.Depth.VolumeByExchangesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Proto3.MarketData.Depth.VolumeByExchangesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Proto3.MarketData.Depth.VolumeByExchangesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=342,
)

_DEPTH = _descriptor.Descriptor(
  name='Depth',
  full_name='Proto3.MarketData.Depth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='Proto3.MarketData.Depth.price', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='Proto3.MarketData.Depth.volume', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume_by_exchanges', full_name='Proto3.MarketData.Depth.volume_by_exchanges', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DEPTH_VOLUMEBYEXCHANGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=342,
)


_DEPTHQUOTE = _descriptor.Descriptor(
  name='DepthQuote',
  full_name='Proto3.MarketData.DepthQuote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='Proto3.MarketData.DepthQuote.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='Proto3.MarketData.DepthQuote.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_no', full_name='Proto3.MarketData.DepthQuote.sequence_no', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='origin_time', full_name='Proto3.MarketData.DepthQuote.origin_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arrive_time', full_name='Proto3.MarketData.DepthQuote.arrive_time', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_time', full_name='Proto3.MarketData.DepthQuote.server_time', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price_precise', full_name='Proto3.MarketData.DepthQuote.price_precise', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume_precise', full_name='Proto3.MarketData.DepthQuote.volume_precise', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount_precise', full_name='Proto3.MarketData.DepthQuote.amount_precise', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_snap', full_name='Proto3.MarketData.DepthQuote.is_snap', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asks', full_name='Proto3.MarketData.DepthQuote.asks', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bids', full_name='Proto3.MarketData.DepthQuote.bids', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=643,
)


_KLINEDATA = _descriptor.Descriptor(
  name='KlineData',
  full_name='Proto3.MarketData.KlineData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Proto3.MarketData.KlineData.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='Proto3.MarketData.KlineData.exchange', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='Proto3.MarketData.KlineData.symbol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='px_open', full_name='Proto3.MarketData.KlineData.px_open', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='px_high', full_name='Proto3.MarketData.KlineData.px_high', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='px_low', full_name='Proto3.MarketData.KlineData.px_low', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='px_close', full_name='Proto3.MarketData.KlineData.px_close', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='Proto3.MarketData.KlineData.volume', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='Proto3.MarketData.KlineData.resolution', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=646,
  serialized_end=949,
)


_TRADEDATA = _descriptor.Descriptor(
  name='TradeData',
  full_name='Proto3.MarketData.TradeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Proto3.MarketData.TradeData.time', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='Proto3.MarketData.TradeData.price', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='Proto3.MarketData.TradeData.volume', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='Proto3.MarketData.TradeData.symbol', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='Proto3.MarketData.TradeData.exchange', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=952,
  serialized_end=1098,
)

_DEPTH_VOLUMEBYEXCHANGESENTRY.fields_by_name['value'].message_type = _DECIMAL
_DEPTH_VOLUMEBYEXCHANGESENTRY.containing_type = _DEPTH
_DEPTH.fields_by_name['price'].message_type = _DECIMAL
_DEPTH.fields_by_name['volume'].message_type = _DECIMAL
_DEPTH.fields_by_name['volume_by_exchanges'].message_type = _DEPTH_VOLUMEBYEXCHANGESENTRY
_DEPTHQUOTE.fields_by_name['asks'].message_type = _DEPTH
_DEPTHQUOTE.fields_by_name['bids'].message_type = _DEPTH
_KLINEDATA.fields_by_name['px_open'].message_type = _DECIMAL
_KLINEDATA.fields_by_name['px_high'].message_type = _DECIMAL
_KLINEDATA.fields_by_name['px_low'].message_type = _DECIMAL
_KLINEDATA.fields_by_name['px_close'].message_type = _DECIMAL
_KLINEDATA.fields_by_name['volume'].message_type = _DECIMAL
_TRADEDATA.fields_by_name['price'].message_type = _DECIMAL
_TRADEDATA.fields_by_name['volume'].message_type = _DECIMAL
DESCRIPTOR.message_types_by_name['Decimal'] = _DECIMAL
DESCRIPTOR.message_types_by_name['Depth'] = _DEPTH
DESCRIPTOR.message_types_by_name['DepthQuote'] = _DEPTHQUOTE
DESCRIPTOR.message_types_by_name['KlineData'] = _KLINEDATA
DESCRIPTOR.message_types_by_name['TradeData'] = _TRADEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Decimal = _reflection.GeneratedProtocolMessageType('Decimal', (_message.Message,), {
  'DESCRIPTOR' : _DECIMAL,
  '__module__' : 'market_data_pb2'
  # @@protoc_insertion_point(class_scope:Proto3.MarketData.Decimal)
  })
_sym_db.RegisterMessage(Decimal)

Depth = _reflection.GeneratedProtocolMessageType('Depth', (_message.Message,), {

  'VolumeByExchangesEntry' : _reflection.GeneratedProtocolMessageType('VolumeByExchangesEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEPTH_VOLUMEBYEXCHANGESENTRY,
    '__module__' : 'market_data_pb2'
    # @@protoc_insertion_point(class_scope:Proto3.MarketData.Depth.VolumeByExchangesEntry)
    })
  ,
  'DESCRIPTOR' : _DEPTH,
  '__module__' : 'market_data_pb2'
  # @@protoc_insertion_point(class_scope:Proto3.MarketData.Depth)
  })
_sym_db.RegisterMessage(Depth)
_sym_db.RegisterMessage(Depth.VolumeByExchangesEntry)

DepthQuote = _reflection.GeneratedProtocolMessageType('DepthQuote', (_message.Message,), {
  'DESCRIPTOR' : _DEPTHQUOTE,
  '__module__' : 'market_data_pb2'
  # @@protoc_insertion_point(class_scope:Proto3.MarketData.DepthQuote)
  })
_sym_db.RegisterMessage(DepthQuote)

KlineData = _reflection.GeneratedProtocolMessageType('KlineData', (_message.Message,), {
  'DESCRIPTOR' : _KLINEDATA,
  '__module__' : 'market_data_pb2'
  # @@protoc_insertion_point(class_scope:Proto3.MarketData.KlineData)
  })
_sym_db.RegisterMessage(KlineData)

TradeData = _reflection.GeneratedProtocolMessageType('TradeData', (_message.Message,), {
  'DESCRIPTOR' : _TRADEDATA,
  '__module__' : 'market_data_pb2'
  # @@protoc_insertion_point(class_scope:Proto3.MarketData.TradeData)
  })
_sym_db.RegisterMessage(TradeData)


_DEPTH_VOLUMEBYEXCHANGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
